import { Offer } from './models/offer.model';

export const OFFERS: Array<Offer> = [
  {
    position: 'Pre-Intern Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: true,
    salary: [0, 0],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS'],
    timePosted: new Date('2020-08-20T17:00:00'),
  },
  {
    position: 'TEST DATY',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: true,
    salary: [400000, 500000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS'],
    timePosted: new Date('2020-08-07T17:00:00'),
  },
  {
    position: 'Intern Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: true,
    salary: [2000, 2000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T20:10:00'),
  },
  {
    position: 'Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: true,
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T20:20:00'),
  },
  {
    position: 'Baby Junior Java Developer',
    company: 'Spartez',
    location: 'Gdansk',
    remote: false,
    tags: ['Java', 'MoboDB'],
    timePosted: new Date('2020-08-20T13:30:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Spartez',
    location: 'Gdansk',
    remote: false,
    salary: [12000, 16000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T15:35:00'),
  },
  {
    position: 'Senior C# Developer',
    company: 'Intel',
    location: 'Gdansk',
    remote: true,
    salary: [17000, 21000],
    currency: 'PLN',
    tags: ['C#', 'C++'],
    timePosted: new Date('2020-08-20T16:37:00'),
  },
  {
    position: 'Senior Concrete Mixer Operator',
    company: 'Zbych-BUD',
    location: 'Kolbudy',
    remote: false,
    salary: [1680, 1720],
    currency: 'PLN',
    tags: ['Concrete', 'Shovel', 'Beer', 'Notfunny'],
    timePosted: new Date('2020-08-20T09:38:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: false,
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T15:41:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: false,
    salary: [3000, 6000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T06:43:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: false,
    salary: [3000, 6000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T03:46:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: false,
    salary: [3000, 6000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T06:51:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: false,
    salary: [3000, 6000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T07:53:00'),
  },
  {
    position: 'Senior Software Developer',
    company: 'Neoteric',
    location: 'Gdansk',
    remote: false,
    salary: [3000, 6000],
    currency: 'PLN',
    tags: ['JS', 'HTML', 'CSS', 'Angular'],
    timePosted: new Date('2020-08-20T21:54:00'),
  },
];
